In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarr',arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [6]:
arr1 = np.load('myarr.npy')
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.savez('ziparr.npz', x=arr1, y=arr2)

In [10]:
archive_arr = np.load('ziparr.npz')

In [11]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [12]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.savetxt('mytext.txt',arr,delimiter=',')

In [17]:
arr = np.loadtxt('mytext.txt', delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])