In [2]:
import numpy as np

In [8]:
arr = np.arange(50).reshape((5,5,2))
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [17]:
arr.transpose((2,1,0))

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [18]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])