In [1]:
import numpy as np
from pandas import Series, DataFrame 
import pandas as pd

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
 ser1 = Series([1,2,3], index=['X','Y','Z'])

In [8]:
ser2 = Series([4,5], index=['T','U'])

In [9]:
ser1

X    1
Y    2
Z    3
dtype: int64

In [10]:
ser2

T    4
U    5
dtype: int64

In [11]:
pd.concat([ser1, ser2])

X    1
Y    2
Z    3
T    4
U    5
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis=1)

0    1
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN
T  NaN  4.0
U  NaN  5.0

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  X    1
      Y    2
      Z    3
cat2  T    4
      U    5
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns= ['X','Y','Z'])

In [15]:
dframe2 = DataFrame(np.random.randn(3,3), columns= ['Y','Q','X'])

In [16]:
dframe1

X         Y         Z
0 -2.542184  0.073183 -0.439614
1  1.747235 -1.405778  1.713894
2 -0.140554 -1.500117 -0.230405
3  1.858693 -0.857470 -0.749681

In [17]:
dframe2

Y         Q         X
0 -0.338802  0.299140 -1.204304
1 -0.290165  0.921644  0.040813
2  0.342356 -0.463497  0.687010

In [18]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -2.542184  0.073183 -0.439614       NaN
1  1.747235 -1.405778  1.713894       NaN
2 -0.140554 -1.500117 -0.230405       NaN
3  1.858693 -0.857470 -0.749681       NaN
0 -1.204304 -0.338802       NaN  0.299140
1  0.040813 -0.290165       NaN  0.921644
2  0.687010  0.342356       NaN -0.463497

In [20]:
pd.concat([dframe1,dframe2],ignore_index=True) 

X         Y         Z         Q
0 -2.542184  0.073183 -0.439614       NaN
1  1.747235 -1.405778  1.713894       NaN
2 -0.140554 -1.500117 -0.230405       NaN
3  1.858693 -0.857470 -0.749681       NaN
4 -1.204304 -0.338802       NaN  0.299140
5  0.040813 -0.290165       NaN  0.921644
6  0.687010  0.342356       NaN -0.463497