In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(array1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
A = np.random.randn(5)
A

array([-0.43297196,  0.77697251, -0.72447932, -0.82646241,  1.40525322])

In [5]:
B = np.random.randn(5)
B

array([-0.5760172 ,  0.09833119,  1.56014126,  1.49344639,  0.79709622])

In [6]:
np.add(A,B)

array([-1.00898916,  0.8753037 ,  0.83566194,  0.66698399,  2.20234944])

In [7]:
np.maximum(A,B)

array([-0.43297196,  0.77697251,  1.56014126,  1.49344639,  1.40525322])

In [8]:
website = 'https://numpy.org/devdocs/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True